import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"

import "./globals.css"

import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"

import { cn } from "@/lib/utils"
import Toaster from "@/components/ui/Toaster"
import ThemeProvider from "@/components/providers"
import { TailwindIndicator } from "@/components/tailwind-indicator"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            GeistSans.variable,
            GeistMono.variable
            // fontHeading.variable
          )}
        >
          <ThemeProvider
            defaultTheme="system"
            attribute="class"
            disableTransitionOnChange
          >
            {children}
            <TailwindIndicator />
          </ThemeProvider>

          {/* <TailwindIndicator />
            <Analytics />
           */}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
